# Generated by Django 5.1.2 on 2024-10-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ormapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankloan',
            name='accno',
            field=models.IntegerField(primary_key='accno', serialize=False),
        ),
    ]
